stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  # Install dependencies and set up environment
  - apk add --no-cache openjdk11 python3 py3-pip bash
  - python3 -m venv /tmp/venv                  # Create a virtual environment
  - . /tmp/venv/bin/activate                   # Activate the virtual environment
  - pip install --upgrade pip                  # Upgrade pip
  - pip install flask requests                 # Install Python dependencies
  - docker-compose version

build:
  stage: build
  script:
    - echo "Building Java service..."
    - docker build -t java-service:latest -f Dockerfile.java .
    - echo "Building Python service..."
    - docker build -t python-service:latest -f Dockerfile.python .
    - echo "Building all services with Docker Compose..."
    - docker-compose build
  only:
    - project

test:
  stage: test
  script:
    - echo "Starting services for testing..."
    - docker-compose up -d  # Start services in detached mode
    - sleep 5               # Wait for services to initialize

    - echo "Running Java service tests..."
    - javac tests/MainTest.java -cp .:/path/to/junit-5.8.2.jar
    - java -cp .:/path/to/junit-5.8.2.jar org.junit.runner.JUnitCore tests.MainTest

    - echo "Running Python service tests..."
    - python3 -m unittest discover -s tests -p "test_*.py"

    - echo "Stopping services after tests..."
    - docker-compose down
  only:
    - project

deploy:
  stage: deploy
  script:
    - echo "Deploying services..."
    - docker-compose up -d  # Deploy services in detached mode
    - echo "Services deployed successfully!"
  only:
    - project
