stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

image: docker:20.10.7

services:
  - name: docker:20.10-dind
    alias: docker
    command: ["--tls=false"]

before_script:
  - docker info || true
  - docker-compose --version || true

build_services:
  stage: build
  script:
    - docker-compose build
  only:
    - project

test_services:
  stage: test
  script:
    - docker-compose config
    - docker-compose build
  only:
    - project

deploy_services:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - project
  when: manual