stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  DOCKER_NETWORK_MODE: host

image: docker:latest
services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]

before_script:
  - apk update
  - apk add --no-cache 
      docker-compose 
      python3 
      git
  # Diagnostic commands
  - echo "Hostname resolution:"
  - cat /etc/hosts
  - echo "Trying to resolve docker:"
  - nslookup docker || true
  - echo "Checking network interfaces:"
  - ip addr

build_services:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose build
  only:
    - project

test_config:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose config
    - docker-compose build --dry-run
  only:
    - project

deploy_services:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose up -d
  only:
    - project
  when: manual