image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: my-app

before_script:
  - docker info
  - docker-compose version

# Build stage: Build all services
build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
    - docker images
  only:
    - project
    - merge_requests

# Test stage: Run tests
test:
  stage: test
  image: python:3.9
  script:
    - pip install pytest
    # Ensure we have the necessary tools
    - pip install docker-compose
    # Run the dummy test
    - pytest Test/test_dummy.py
  only:
    - project
    - merge_requests

# Deploy stage: Deploy to production
deploy:
  stage: deploy
  script:
    # Stop existing containers
    - docker-compose -f docker-compose.yml down
    # Pull latest images
    - docker-compose -f docker-compose.yml pull
    # Start new containers
    - docker-compose -f docker-compose.yml up -d
  only:
    - project
  environment:
    name: production
    action: start
