stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: finalproject

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
  # Ensure Docker and Docker Compose are working
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    # Use the exact same docker-compose command you use locally
    - docker-compose build
  only:
    - project

test:
  stage: test
  script:
    # Start services in detached mode
    - docker-compose up -d
    # Wait for services to start
    - sleep 15
    # Check container status
    - docker-compose ps
    # Run tests
    - docker-compose exec -T service2 pytest ./Test/test_dummy.py
  after_script:
    # Always attempt to stop and remove containers
    - docker-compose down
  only:
    - project

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - project