stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
  - apk add --no-cache net-tools
  - docker info
  # Print out the directory structure and file contents for debugging
  - pwd
  - ls -R
  - cat nginx/nginx.conf

build:
  stage: build
  script:
    # Ensure the nginx.conf file exists and has correct permissions
    - chmod 644 nginx/nginx.conf
    - docker-compose -f docker-compose.yml build
  only:
    - project

test:
  stage: test
  script:
    # Additional debugging steps
    - docker-compose -f docker-compose.yml config
    - docker-compose -f docker-compose.yml up -d
    - sleep 10
    - docker-compose ps
    - docker-compose logs
    # Run tests
    - docker-compose -f docker-compose.yml exec -T service2 pytest ./Test/test_dummy.py
  after_script:
    - docker-compose -f docker-compose.yml down
  only:
    - project

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - project