stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml exec service1-1 pytest /app/tests
    - docker-compose -f docker-compose.yml exec service1-2 pytest /app/tests
    - docker-compose -f docker-compose.yml exec service1-3 pytest /app/tests
    - docker-compose -f docker-compose.yml exec service2 pytest /app/tests
  after_script:
    - docker-compose -f docker-compose.yml down

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - project