stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

image: docker:20.10.7  # Use a Docker image for the runner
services:
  - docker:20.10-dind  # Ensure Docker is available for later stages

before_script:
  - docker info  # Check Docker info to ensure it's running

# Build Stage
build:
  stage: build
  script:
    - echo "Building services..."
    - docker-compose build
  only:
    - project

# Test Stage
test:
  stage: test
  script:
    - echo "Running dummy test..."
    - pip install pytest
    - pytest tests/
  only:
    - project

# Deploy Stage
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker-compose up -d
  only:
    - project