stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind # Docker-in-Docker service for Docker commands

before_script:
  # Install necessary packages before running any script
  - apk add --no-cache docker-compose
  - apk add --no-cache net-tools
  - docker info # Check Docker info for troubleshooting
  - docker-compose -f docker-compose.yml down # Make sure to clean up any previous containers
  # Remove any process that may be occupying port 5000
  - if netstat -tuln | grep ':5000' >/dev/null ; then kill -9 $(netstat -tuln | grep ':5000' | awk '{print $7}' | cut -d'/' -f1) ; fi

build:
  stage: build
  script:
    # Build your Docker images using docker-compose
    - docker-compose -f docker-compose.yml build
  only:
    - project

test:
  stage: test
  script:
    # Start the services in detached mode
    - docker-compose -f docker-compose.yml up -d
    # Wait for services to be fully up and running
    - sleep 10 # Give some time for the containers to fully initialize
    # Run tests inside the running containers for each service
    - docker-compose -f docker-compose.yml exec -T service1-1 pytest ./Test
    - docker-compose -f docker-compose.yml exec -T service2 pytest ./Test
  after_script:
    # Stop the services after testing
    - docker-compose -f docker-compose.yml down
  only:
    - project

deploy:
  stage: deploy
  script:
    # Deploy services in detached mode
    - docker-compose -f docker-compose.yml up -d
  only:
    - project