stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
  - apk add --no-cache net-tools 
  - docker info
  - docker-compose -f docker-compose.yml down  
  - if netstat -tuln | grep ':5000' >/dev/null ; then kill -9 $(netstat -tuln | grep ':5000' | awk '{print $7}' | cut -d'/' -f1) ; fi  # Ensure port 5000 is free

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml exec service1-1 pytest /Test
    - docker-compose -f docker-compose.yml exec service1-2 pytest /Test
    - docker-compose -f docker-compose.yml exec service1-3 pytest /Test
    - docker-compose -f docker-compose.yml exec service2 pytest /Test
  after_script:
    - docker-compose -f docker-compose.yml down

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - project