# stages:
#   - build
#   - test
#   - deploy

# variables:
#   DOCKER_DRIVER: overlay2

# services:
#   - docker:dind

# before_script:
#   - apk add --no-cache docker-compose
#   - docker info

# build:
#   stage: build
#   script:
#     - docker-compose -f docker-compose.yml build

# test:
#   stage: test
#   script:
#     - docker-compose -f docker-compose.yml up -d
#     - docker-compose -f docker-compose.yml exec service1-1 pytest /app/tests
#     - docker-compose -f docker-compose.yml exec service1-2 pytest /app/tests
#     - docker-compose -f docker-compose.yml exec service1-3 pytest /app/tests
#     - docker-compose -f docker-compose.yml exec service2 pytest /app/tests
#   after_script:
#     - docker-compose -f docker-compose.yml down

# deploy:
#   stage: deploy
#   script:
#     - docker-compose -f docker-compose.yml up -d
#   only:
#     - project

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
  - docker info
  - docker-compose -f docker-compose.yml down  # Ensure previous containers are stopped and removed
  - if lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null ; then kill -9 $(lsof -t -i:5000) ; fi  # Ensure port 5000 is free

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml exec service1-1 pytest /app/tests
    - docker-compose -f docker-compose.yml exec service1-2 pytest /app/tests
    - docker-compose -f docker-compose.yml exec service1-3 pytest /app/tests
    - docker-compose -f docker-compose.yml exec service2 pytest /app/tests
  after_script:
    - docker-compose -f docker-compose.yml down

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - project