stages:
  - build
  - test
  - deploy

services:
  - name: docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "Building all services..."
    - docker-compose build  # Build all services
    - docker images  # Display built images
  only:
    - project

test:
  stage: test
  script:
    - echo "Running tests..."
    - docker-compose up --build test  # Build and run the test service
    - docker-compose down  # Clean up after tests
  only:
    - project

deploy:
  stage: deploy
  script:
    - echo "Deploying services..."
    - docker-compose up -d  # Start all services in detached mode
    - docker-compose ps  # Show running containers
  only:
    - project
