```yaml
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

image: docker:latest
services:
  - docker:dind

before_script:
  - apk update
  - apk add --no-cache 
      docker-compose 
      python3 
      git
  - docker info
  - docker-compose version

build_services:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose build
  only:
    - project

test_config:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose config
    - docker-compose build --dry-run
  only:
    - project

deploy_services:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose up -d
  only:
    - project
  when: manual
```