version: '3.8'

services:
  service1-1:
    build:
      context: ./service1
    networks:
      - app-network

  service1-2:
    build:
      context: ./service1
    networks:
      - app-network

  service1-3:
    build:
      context: ./service1
    networks:
      - app-network

  service2:
    build:
      context: ./service2
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8198:80"
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2
    build:
      context: ./nginx
      dockerfile: Dockerfile  # Specify a custom Dockerfile
    networks:
      - app-network

  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - nginx
    

networks:
  app-network:
    driver: bridge
