version: '3.8'

services:
  service1-1:
    build:
      context: ./service1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml  
    networks:
      - app-network

  service1-2:
    build:
      context: ./service1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml  
    networks:
      - app-network

  service1-3:
    build:
      context: ./service1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml  
    networks:
      - app-network

  service2:
    build:
      context: ./service2
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8198:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./web:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - service1-1
      - service1-2
      - service1-3

networks:
  app-network: