version: '3.8'

services:
  service1-1:
    build: ./service1
    volumes:
      - ./service1:/app/service1:ro
    networks:
      - app-network

  service1-2:
    build: ./service1
    volumes:
      - ./service1:/app/service1:ro
    networks:
      - app-network

  service1-3:
    build: ./service1
    volumes:
      - ./service1:/app/service1:ro
    networks:
      - app-network

  service2:
    build: ./service2
    ports:
      - "5000:5000"
    volumes:
      - ./service2:/app/service2:ro
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8198:80"
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
