version: '3.8'

services:
  service1-1:
    build:
      context: ./service1
    networks:
      - app-network

  service1-2:
    build:
      context: ./service1
    networks:
      - app-network

  service1-3:
    build:
      context: ./service1
    networks:
      - app-network

  service2:
    build:
      context: ./service2
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8198:80"
    networks:
      - app-network
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro

  test:
    image: python:3.12  # Use Python to run tests
    working_dir: /app
    volumes:
      - .:/app  # Mount the project directory
    networks:
      - app-network
    depends_on:
      - nginx
    command: >
      sh -c "
      pip install requests unittest-xml-reporting &&
      python3 -m unittest discover -s tests -p 'test_gateway.py'
      "

networks:
  app-network:
    driver: bridge
