
version: '3.8'

# First instance of Service1
services:
  service1-1:
    build:
      context: ./service1
    networks:
      - app-network

# Second instance of Service1
  service1-2:
    build:
      context: ./service1
    networks:
      - app-network

# Third instance of Service1
  service1-3:
    build:
      context: ./service1
    networks:
      - app-network

# Service2 instance
  service2:
    build:
      context: ./service2
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - app-network

 # Nginx: Reverse proxy and traffic router
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    ports:
      - "8198:8198" # Port or browser traffic
      - "8197:8197" # Port for REST API tests
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2
    networks:
      - app-network

# Test service: For running tests on the application
  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge
