version: '3.8'

services:
  service1-1:
    build:
      context: ./service1
    networks:
      - app-network

  service1-2:
    build:
      context: ./service1
    networks:
      - app-network

  service1-3:
    build:
      context: ./service1
    networks:
      - app-network

  service2:
    build:
      context: ./service2
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8198:80"
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2
    build:
      context: ./nginx
      dockerfile: Dockerfile  # Specify a custom Dockerfile
    networks:
      - app-network

  test:
    image: python:3.12
    working_dir: /app  # Ensure the working directory is set to the project root
    volumes:
      - .:/app  # Mount the entire project directory into the container
    networks:
      - app-network
    depends_on:
      - nginx  # Wait for nginx service to start
    command: >
      sh -c "
      pip install requests unittest-xml-reporting &&
      python3 -m unittest discover -s /app/tests -p 'test_*.py' || exit 1
      "

networks:
  app-network:
    driver: bridge
